### ISSUE TITLE
Unable to list posts using custom taxonomies

### ISSUE THREAD

**Issue by chopraaa** [onweru/hugo-swift-theme#13]
I'm not sure if this is related to the theme but this seemed like the best place to start.

I'm using custom taxonomies defined in my post like:

```
actors:
  - Bruce Willis
```

And the page for `example.com/actors` is getting created automatically and the list of actors gets populated on it's own using `layouts/_default/list.html` on it's own.

What I'm not sure about is how to use `list.html` to display excerpts for posts that have Bruce Willis as the actor. So ideally `example.com/actors/bruce-willis` should display a list of posts that have the custom taxonomy.

Edit - This is possible by creating a directory `content/actors/bruce-willis` but I'm looking for this to be done automatically if possible.

Edit 2 - Issue with the dev server. 🤦‍♂

**Comment by VincentTam** [comment]
> I'm not sure if this is related to the theme but this seemed like the best place to start.

If your issue concerns any file provided by this theme, this repo's issues page is definitely *the* place to raise this.

> I'm using custom taxonomies defined in my post like:

If your custom file is derived from any file in this theme, you're welcome to post an issue here, but if you can reframe your question in a more general way, [Hugo Discourse](https://discourse.gohugo.io/) is a better place to ask due to its large amount of users.  From my experience there, you're going to get a response (from an experienced Hugo user) in an hour or so.

**Comment by onweru** [comment]
After fixing #27 in 6ba83cb288d1675d8e758633a167ee77e4a9ba0d, taxonomies seem to be broken
