### ISSUE TITLE
Can we replace all instances of forEach in JS?

### ISSUE THREAD

**Issue by VincentTam** [onweru/hugo-swift-theme#31]
In `assets/js/index.js`, there're several instances of `forEach`, which is [95% slower than `for`](https://coderwall.com/p/kvzbpa/don-t-use-array-foreach-use-for-instead).  I wonder if they can be replaced by `for`.

**Comment by onweru** [comment]
The reason I use `forEach` is because it's a cleaner functional approach. Please see the comments section of the link you cited. See the comments by **KirbyWallace, the-simian, stdio, syifaazzahra &  Konstrukt**.

I think  `map()` [would be a better replacement](https://codeburst.io/javascript-map-vs-foreach-f38111822c0f)

**Comment by VincentTam** [comment]
Thanks for pointing the **bolded comments**.  I'm working on your JS for the project.  Thanks to `forEach`, the syntax can be more beautiful, even though the upcoming modified JS would be a sphaghetti of JS + Hugo code.

```js
  function clearForm() {
    resetReplyTarget();
    // empty all text & hidden fields
    elems('.form_input').forEach((form_input) => {form_input.value = ''});
  }
```
